const khodamData = [
    "Khodam Harimau Bangkit",
    "Khodam Macan Terbang",
    "Khodam Singa Perkasa",
    "Khodam Naga Tersembunyi",
    "Khodam Garuda Perkasa",
    "Khodam Phoenix Bersinar",
    "Khodam Unicorn Gemilang",
    "Khodam Griffin Terbang",
    "Khodam Pegasus Terbang",
    "Khodam Sphinx Tertawa",
    "Khodam Centaur Cerdik",
    "Khodam Feniks Agung",
    "Khodam Cerberus Setia",
    "Khodam Hydra Kekal",
    "Khodam Dragon Naga",
    "Khodam Basilisk Beracun",
    "Khodam Minotaur Kuat",
    "Khodam Yeti Es",
    "Khodam Bigfoot Misterius",
    "Khodam Kraken Lautan",
    "Khodam Chupacabra Tersembunyi",
    "Khodam Wendigo Kedinginan",
    "Khodam Kitsune Ceria",
    "Khodam Tanuki Pintar",
    "Khodam Kappa Berair",
    "Khodam Tengu Angin",
    "Khodam Oni Berkepala Tiga",
    "Khodam Raiju Petir",
    "Khodam Kamaitachi Taji",
    "Khodam Bakeneko Licik",
    "Khodam Nue Transformasi",
    "Khodam Komainu Setia",
    "Khodam Kirin Berkilau",
    "Khodam Tsuchigumo Laba-laba",
    "Khodam Jorogumo Cantik",
    "Khodam Tanuki Gemuk",
    "Khodam Okami Suci",
    "Khodam Inugami Setia",
    "Khodam Tanuki Mencuri",
    "Khodam Noppera-bo Wajah Kosong",
    "Khodam Abumi-guchi Pengerat",
    "Khodam Aka Manto Merah",
    "Khodam Ashiarai Yashiki Kaki Raksasa",
    "Khodam Bake-kujira Paus Hantu",
    "Khodam Buruburu Gemetar",
    "Khodam Dorotabo Tani Menyusup",
    "Khodam Funayurei Hantu Laut",
    "Khodam Gasha-dokuro Tengkorak Raksasa",
    "Khodam Hanako-san Toilet",
    "Khodam Hitodama Api Terbang",
    "Khodam Ikiryo Semangat Terpisah",
    "Khodam Jinmenju Pohon Wajah",
    "Khodam Jubokko Pohon Darah",
    "Khodam Kamikiri Seringai",
    "Khodam Kawa-no-kami Dewa Sungai",
    "Khodam Kuchisake-onna Wanita Bermulut Potong",
    "Khodam Mokumokuren Mata Banyak",
    "Khodam Mujina Pemalu",
    "Khodam Namahage Setan Pengusir",
    "Khodam Nurarihyon Kepala Hijau",
    "Khodam Noppera-bo Wajah Kosong",
    "Khodam Nue Transformasi",
    "Khodam Nuppeppo Lempung Gemuk",
    "Khodam Nurarihyon Kepala Hijau",
    "Khodam Oboroguruma Kereta Hantu",
    "Khodam Odoro-odoro Odoro-odoro",
    "Khodam Ohaguro-bettari Pahatan Gigi Hitam",
    "Khodam Okiku Ningyou Boneka",
    "Khodam Oshiroi Baba Nyonya Berpakaian Putih",
    "Khodam Rokuro-kubi Kepala Terpisah",
    "Khodam Satori Pemikiran",
    "Khodam Shichinin Misaki Pengganggu",
    "Khodam Shikigami Hantu Tertawa",
    "Khodam Tanuki Menjadi Diri Sendiri",
    "Khodam Tengu Berburu",
    "Khodam Tsuchigumo Laba-laba",
    "Khodam Umibozu Perompak Lautan",
    "Khodam Wanyuudou Roda Hantu",
    "Khodam Yama-uba Raksasa Gunung",
    "Khodam Yurei Hantu Sedih",
    "Khodam Zashiki-warashi Setan Kecil",
    "Khodam Yama-uba Raksasa Gunung",
    "Khodam Nurarihyon Kepala Hijau",
    "Khodam Noppera-bo Wajah Kosong",
    "Khodam Nue Transformasi",
    "Khodam Nuppeppo Lempung Gemuk",
    "Khodam Nurarihyon Kepala Hijau",
    "Khodam Oboroguruma Kereta Hantu",
    "Khodam Odoro-odoro Odoro-odoro",
    "Khodam Ohaguro-bettari Pahatan Gigi Hitam",
    "Khodam Okiku Ningyou Boneka",
    "Khodam Oshiroi Baba Nyonya Berpakaian Putih",
    "Khodam Rokuro-kubi Kepala Terpisah",
    "Khodam Satori Pemikiran",
    "Khodam Shichinin Misaki Pengganggu",
    "Khodam Shikigami Hantu Tertawa",
    "Khodam Tanuki Menjadi Diri Sendiri",
    "Khodam Tengu Berburu",
    "Khodam Tsuchigumo Laba-laba",
    "Khodam Umibozu Perompak Lautan",
    "Khodam Wanyuudou Roda Hantu",
    "Khodam Yama-uba Raksasa Gunung",
    "Khodam Yurei Hantu Sedih",
    "Khodam Zashiki-warashi Setan Kecil",
    // Data tambahan hingga 300+
    "Khodam Merak Megah",
    "Khodam Singa Laut",
    "Khodam Elang Api",
    "Khodam Gajah Perkasa",
    "Khodam Ular Sanca",
    "Khodam Kalajengking Petir",
    "Khodam Laba-laba Raksasa",
    "Khodam Kumbang Tanduk",
    "Khodam Badak Bercula",
    "Khodam Kuda Nil",
    "Khodam Buaya Darat",
    "Khodam Komodo Purba",
    "Khodam Burung Hantu",
    "Khodam Rajawali Emas",
    "Khodam Merpati Suci",
    "Khodam Bangau Sakti",
    "Khodam Burung Cendrawasih",
    "Khodam Jalak Bali",
    "Khodam Kakatua Jambul",
    "Khodam Elang Bondol",
    "Khodam Gagak Peramal",
    "Khodam Kelelawar Vampir",
    "Khodam Tikus Gaib",
    "Khodam Kelinci Bulan",
    "Khodam Rubah Api",
    "Khodam Serigala Abu",
    "Khodam Beruang Kutub",
    "Khodam Panda Sakti",
    "Khodam Koala Pemimpi",
    "Khodam Kangguru Lincah",
    "Khodam Platipus Ajaib",
    "Khodam Trenggiling Pelindung",
    "Khodam Landak Penyergap",
    "Khodam Musang Licik",
    "Khodam Luwak Penghasil",
    "Khodam Berang-berang",
    "Khodam Beruk Penyembuh",
    "Khodam Lutung Kasarung",
    "Khodam Monyet Sakti",
    "Khodam Orangutan Bijak",
    "Khodam Gorilla Perkasa",
    "Khodam Simpanse Cerdas",
    "Khodam Babi Hutan",
    "Khodam Kancil Pintar",
    "Khodam Kijang Lari",
    "Khodam Rusa Bertanduk",
    "Khodam Kambing Gunung",
    "Khodam Domba Keberuntungan",
    "Khodam Sapi Perah",
    "Khodam Kerbau Banteng",
    "Khodam Unta Padang Pasir",
    "Khodam Llama Andes",
    "Khodam Alpaca Berbulu",
    "Khodam Zebra Loreng",
    "Khodam Keledai Kerja",
    "Khodam Kuda Nil Air",
    "Khodam Walrus Gading",
    "Khodam Anjing Laut",
    "Khodam Singa Laut",
    "Khodam Paus Pembunuh",
    "Khodam Lumba-lumba",
    "Khodam Hiu Putih",
    "Khodam Pari Manta",
    "Khodam Gurita Raksasa",
    "Khodam Cumi-cumi",
    "Khodam Ubur-ubur",
    "Khodam Bintang Laut",
    "Khodam Teripang Emas",
    "Khodam Kepiting Samurai",
    "Khodam Lobster Merah",
    "Khodam Udang Karang",
    "Khodam Ikan Koi",
    "Khodam Arwana Emas",
    "Khodam Ikan Mas Koki",
    "Khodam Ikan Cupang",
    "Khodam Ikan Pari",
    "Khodam Ikan Hiu Martil",
    "Khodam Ikan Badut",
    "Khodam Ikan Layaran",
    "Khodam Ikan Todak",
    "Khodam Ikan Terbang",
    "Khodam Ikan Lele",
    "Khodam Ikan Gurame",
    "Khodam Ikan Nila",
    "Khodam Ikan Bandeng",
    "Khodam Ikan Salmon",
    "Khodam Ikan Tuna",
    "Khodam Ikan Tongkol",
    "Khodam Ikan Tenggiri",
    "Khodam Ikan Kakap",
    "Khodam Ikan Kerapu",
    "Khodam Ikan Baronang",
    "Khodam Ikan Bawal",
    "Khodam Ikan Belanak",
    "Khodam Ikan Gabus",
    "Khodam Ikan Patin",
    "Khodam Ikan Sarden",
    "Khodam Ikan Makarel",
    "Khodam Ikan Herring",
    "Khodam Ikan Kod",
    "Khodam Ikan Halibut",
    "Khodam Ikan Flounder",
    "Khodam Ikan Sole",
    "Khodam Ikan Plaice",
    "Khodam Ikan Turbot",
    "Khodam Ikan John Dory",
    "Khodam Ikan Monkfish",
    "Khodam Ikan Anglerfish",
    "Khodam Ikan Dragonfish",
    "Khodam Ikan Viperfish",
    "Khodam Ikan Gulper Eel",
    "Khodam Ikan Oarfish",
    "Khodam Ikan Sunfish",
    "Khodam Ikan Pufferfish",
    "Khodam Ikan Blowfish",
    "Khodam Ikan Porcupinefish",
    "Khodam Ikan Cowfish",
    "Khodam Ikan Boxfish",
    "Khodam Ikan Triggerfish",
    "Khodam Ikan Filefish",
    "Khodam Ikan Surgeonfish",
    "Khodam Ikan Tang",
    "Khodam Ikan Rabbitfish",
    "Khodam Ikan Parrotfish",
    "Khodam Ikan Wrasse",
    "Khodam Ikan Grouper",
    "Khodam Ikan Snapper",
    "Khodam Ikan Emperor",
    "Khodam Ikan Sweetlips",
    "Khodam Ikan Grunt",
    "Khodam Ikan Croaker",
    "Khodam Ikan Drum",
    "Khodam Ikan Goatfish",
    "Khodam Ikan Mullet",
    "Khodam Ikan Barracuda",
    "Khodam Ikan Wahoo",
    "Khodam Ikan Kingfish",
    "Khodam Ikan Amberjack",
    "Khodam Ikan Trevally",
    "Khodam Ikan Pompano",
    "Khodam Ikan Permit",
    "Khodam Ikan Palometa",
    "Khodam Ikan Lookdown",
    "Khodam Ikan Moonfish",
    "Khodam Ikan Opah",
    "Khodam Ikan Louvar",
    "Khodam Ikan Escolar",
    "Khodam Ikan Oilfish",
    "Khodam Ikan Snake Mackerel",
    "Khodam Ikan Lancetfish",
    "Khodam Ikan Daggerfish",
    "Khodam Ikan Frostfish",
    "Khodam Iken Scabbardfish",
    "Khodam Ikan Cutlassfish",
    "Khodam Ikan Ribbonfish",
    "Khodam Ikan Hairtail",
    "Khodam Ikan Saury",
    "Khodam Ikan Needlefish",
    "Khodam Ikan Halfbeak",
    "Khodam Ikan Flyingfish",
    "Khodam Ikan Garfish",
    "Khodam Ikan Ballyhoo",
    "Khodam Ikan Houndfish",
    "Khodam Ikan Skipping",
    "Khodam Ikan Bichir",
    "Khodam Ikan Reedfish",
    "Khodam Ikan Sturgeon",
    "Khodam Ikan Paddlefish",
    "Khodam Ikan Bowfin",
    "Khodam Ikan Garpike",
    "Khodam Ikan Arowana",
    "Khodam Ikan Butterflyfish",
    "Khodam Ikan Angelfish",
    "Khodam Ikan Damselfish",
    "Khodam Ikan Clownfish",
    "Khodam Ikan Anemonefish",
    "Khodam Ikan Chromis",
    "Khodam Ikan Demoiselle",
    "Khodam Ikan Sergeant Major",
    "Khodam Ikan Blue Devil",
    "Khodam Iken Jewel Damsel",
    "Khodam Ikan Humbug",
    "Khodam Ikan Talma",
    "Khodam Iken Sweeper",
    "Khodam Ikan Cardinalfish",
    "Khodam Iken Bigeye",
    "Khodam Iken Glassfish",
    "Khodam Ikan Snapper",
    "Khodam Ikan Fusilier",
    "Khodam Ikan Goatfish",
    "Khodam Ikan Emperor",
    "Khodam Ikan Sweetlips",
    "Khodam Ikan Grunt",
    "Khodam Ikan Croaker",
    "Khodam Ikan Drum",
    "Khodam Ikan Goatfish",
    "Khodam Ikan Mullet",
    "Khodam Ikan Barracuda",
    "Khodam Ikan Wahoo",
    "Khodam Ikan Kingfish",
    "Khodam Ikan Amberjack",
    "Khodam Ikan Trevally",
    "Khodam Ikan Pompano",
    "Khodam Ikan Permit",
    "Khodam Ikan Palometa",
    "Khodam Ikan Lookdown",
    "Khodam Ikan Moonfish",
    "Khodam Ikan Opah",
    "Khodam Ikan Louvar",
    "Khodam Ikan Escolar",
    "Khodam Ikan Oilfish",
    "Khodam Ikan Snake Mackerel",
    "Khodam Ikan Lancetfish",
    "Khodam Ikan Daggerfish",
    "Khodam Ikan Frostfish",
    "Khodam Iken Scabbardfish",
    "Khodam Ikan Cutlassfish",
    "Khodam Ikan Ribbonfish",
    "Khodam Ikan Hairtail",
    "Khodam Ikan Saury",
    "Khodam Ikan Needlefish",
    "Khodam Ikan Halfbeak",
    "Khodam Ikan Flyingfish",
    "Khodam Ikan Garfish",
    "Khodam Ikan Ballyhoo",
    "Khodam Ikan Houndfish",
    "Khodam Ikan Skipping",
    "Khodam Ikan Bichir",
    "Khodam Ikan Reedfish",
    "Khodam Ikan Sturgeon",
    "Khodam Ikan Paddlefish",
    "Khodam Ikan Bowfin",
    "Khodam Ikan Garpike",
    "Khodam Ikan Arowana",
    "Khodam Ikan Butterflyfish",
    "Khodam Ikan Angelfish",
    "Khodam Ikan Damselfish",
    "Khodam Ikan Clownfish",
    "Khodam Ikan Anemonefish",
    "Khodam Ikan Chromis",
    "Khodam Ikan Demoiselle",
    "Khodam Ikan Sergeant Major",
    "Khodam Ikan Blue Devil",
    "Khodam Iken Jewel Damsel",
    "Khodam Ikan Humbug",
    "Khodam Ikan Talma",
    "Khodam Iken Sweeper",
    "Khodam Ikan Cardinalfish",
    "Khodam Iken Bigeye",
    "Khodam Iken Glassfish",
    "Khodam Ikan Snapper",
    "Khodam Ikan Fusilier",
    "Khodam Ikan Goatfish",
    "Khodam Ikan Emperor",
    "Khodam Ikan Sweetlips",
    "Khodam Ikan Grunt",
    "Khodam Ikan Croaker",
    "Khodam Ikan Drum",
    "Khodam Ikan Goatfish",
    "Khodam Ikan Mullet",
    "Khodam Ikan Barracuda",
    "Khodam Ikan Wahoo",
    "Khodam Ikan Kingfish",
    "Khodam Ikan Amberjack",
    "Khodam Ikan Trevally",
    "Khodam Ikan Pompano",
    "Khodam Ikan Permit",
    "Khodam Ikan Palometa",
    "Khodam Ikan Lookdown",
    "Khodam Ikan Moonfish",
    "Khodam Ikan Opah",
    "Khodam Ikan Louvar",
    "Khodam Ikan Escolar",
    "Khodam Ikan Oilfish",
    "Khodam Ikan Snake Mackerel",
    "Khodam Ikan Lancetfish",
    "Khodam Ikan Daggerfish",
    "Khodam Ikan Frostfish",
    "Khodam Iken Scabbardfish",
    "Khodam Ikan Cutlassfish",
    "Khodam Ikan Ribbonfish",
    "Khodam Ikan Hairtail",
    "Khodam Ikan Saury",
    "Khodam Ikan Needlefish",
    "Khodam Ikan Halfbeak",
    "Khodam Ikan Flyingfish",
    "Khodam Ikan Garfish",
    "Khodam Ikan Ballyhoo",
    "Khodam Ikan Houndfish",
    "Khodam Ikan Skipping",
    "Khodam Ikan Bichir",
    "Khodam Ikan Reedfish",
    "Khodam Ikan Sturgeon",
    "Khodam Ikan Paddlefish",
    "Khodam Ikan Bowfin",
    "Khodam Ikan Garpike",
    "Khodam Ikan Arowana",
    "Khodam Ikan Butterflyfish",
    "Khodam Ikan Angelfish",
    "Khodam Ikan Damselfish",
    "Khodam Ikan Clownfish",
    "Khodam Ikan Anemonefish",
    "Khodam Ikan Chromis",
    "Khodam Ikan Demoiselle",
    "Khodam Ikan Sergeant Major",
    "Khodam Ikan Blue Devil",
    "Khodam Iken Jewel Damsel",
    "Khodam Ikan Humbug",
    "Khodam Ikan Talma",
    "Khodam Iken Sweeper",
    "Khodam Ikan Cardinalfish",
    "Khodam Iken Bigeye",
    "Khodam Iken Glassfish",
];

const axios = require('axios');

// Daftar khodam dan deskripsinya untuk simulasi (300+ items)
const khodamList = [
    { name: "Elang Emas", desc: "Melambangkan ketajaman pandangan, kebijaksanaan, dan kekuasaan. Pemiliknya cenderung berjiwa pemimpin dan visioner." },
    { name: "Harimau Putih", desc: "Simbol keberanian, kekuatan, dan perlindungan. Membawa aura wibawa dan ketegasan." },
    { name: "Naga Sakti", desc: "Mewakili kebijaksanaan tertinggi, kekuatan gaib, dan kemakmuran. Sering dikaitkan dengan keberuntungan besar." },
    { name: "Macan Kumbang", desc: "Lambang kelincahan, strategi, dan kemampuan beradaptasi dalam situasi sulit." },
    { name: "Kuda Terbang", desc: "Melambangkan kebebasan, kecepatan meraih cita-cita, dan semangat petualangan." },
    { name: "Ular Naga", desc: "Simbol transformasi, penyembuhan, dan pengetahuan tersembunyi." },
    { name: "Rajawali", desc: "Mewakili fokus, presisi, dan kemampuan untuk melihat gambaran besar dari ketinggian." },
    { name: "Singa Api", desc: "Lambang semangat pantang menyerah, passion, dan kepemimpinan yang memotivasi." },
    { name: "Merak Megah", desc: "Simbol keanggunan, kecantikan, dan kebanggaan. Membawa aura kemewahan dan perhatian." },
    { name: "Gajah Perkasa", desc: "Melambangkan kekuatan, kebijaksanaan, dan memori yang kuat. Pemiliknya cenderung sabar dan tepercaya." },
    { name: "Kalajengking Petir", desc: "Lambang perlindungan, ketajaman, dan kemampuan bertahan dalam kondisi sulit." },
    { name: "Badak Bercula", desc: "Simbol kekuatan fisik, ketahanan, dan perlindungan terhadap bahaya." },
    { name: "Buaya Darat", desc: "Mewakili kesabaran, strategi, dan kekuatan tersembunyi yang siap muncul saat dibutuhkan." },
    { name: "Komodo Purba", desc: "Lambang kekuatan purba, ketahanan, dan warisan leluhur yang kuat." },
    { name: "Burung Hantu", desc: "Simbol kebijaksanaan, misteri, dan kemampuan melihat di kegelapan." },
    { name: "Merpati Suci", desc: "Melambangkan perdamaian, cinta, dan kesucian hati." },
    { name: "Bangau Sakti", desc: "Simbol umur panjang, kebahagiaan, dan keberuntungan dalam kehidupan." },
    { name: "Burung Cendrawasih", desc: "Lambang keindahan, keunikan, dan ekspresi diri yang bebas." },
    { name: "Gagak Peramal", desc: "Mewakili intuisi, ramalan, dan koneksi dengan dunia spiritual." },
    { name: "Kelelawar Vampir", desc: "Simbol adaptasi, kehidupan malam, dan kemampuan bertahan dalam kondisi ekstrem." },
    { name: "Rubah Api", desc: "Lambang kecerdikan, kelincahan, dan kemampuan beradaptasi dengan perubahan." },
    { name: "Serigala Abu", desc: "Melambangkan kesetiaan, kerja tim, dan insting yang kuat." },
    { name: "Beruang Kutub", desc: "Simbol kekuatan, ketahanan dalam kondisi ekstrem, dan perlindungan." },
    { name: "Panda Sakti", desc: "Lambang kedamaian, keseimbangan, dan kekuatan yang lembut." },
    { name: "Koala Pemimpi", desc: "Mewakili ketenangan, kenyamanan, dan kehidupan yang santai." },
    { name: "Kangguru Lincah", desc: "Simbol mobilitas, kekuatan kaki, dan kemampuan melompati rintangan." },
    { name: "Platipus Ajaib", desc: "Lambang keunikan, adaptasi, dan kombinasi berbagai kemampuan." },
    { name: "Landak Penyergap", desc: "Melambangkan pertahanan diri, kewaspadaan, dan kemampuan melindungi diri." },
    { name: "Musang Licik", desc: "Simbol kelicikan, strategi, dan kemampuan menyelesaikan masalah dengan cara tidak biasa." },
    { name: "Luwak Penghasil", desc: "Lambang produktivitas, transformasi, dan menciptakan nilai dari hal sederhana." },
    { name: "Berang-berang", desc: "Mewakili kerja keras, pembangunan, dan kehidupan keluarga yang harmonis." },
    { name: "Beruk Penyembuh", desc: "Simbol penyembuhan, empati, dan kemampuan memahami orang lain." },
    { name: "Lutung Kasarung", desc: "Lambang misteri, spiritualitas, dan koneksi dengan alam gaib." },
    { name: "Monyet Sakti", desc: "Melambangkan kecerdasan, kelincahan, dan kemampuan belajar dengan cepat." },
    { name: "Orangutan Bijak", desc: "Simbol kebijaksanaan, kesabaran, dan kedamaian batin." },
    { name: "Gorilla Perkasa", desc: "Lambang kekuatan fisik, kepemimpinan, dan perlindungan terhadap keluarga." },
    { name: "Simpanse Cerdas", desc: "Mewakili kecerdasan, kemampuan memecahkan masalah, dan kehidupan sosial." },
    { name: "Kancil Pintar", desc: "Simbol kecerdikan, kemampuan berbicara, dan menyelesaikan masalah dengan akal." },
    { name: "Kijang Lari", desc: "Lambang kecepatan, kelincahan, dan kemampuan menghindari bahaya." },
    { name: "Rusa Bertanduk", desc: "Melambangkan keanggunan, spiritualitas, dan koneksi dengan alam." },
    { name: "Kambing Gunung", desc: "Simbol ketahanan, keseimbangan, dan kemampuan mencapai tujuan tinggi." },
    { name: "Domba Keberuntungan", desc: "Lambang kemakmuran, kesuburan, dan kehidupan yang damai." },
    { name: "Sapi Perah", desc: "Mewakili kemakmuran, kesuburan, dan pemberian kehidupan." },
    { name: "Kerbau Banteng", desc: "Simbol kekuatan, kerja keras, dan ketahanan fisik." },
    { name: "Unta Padang Pasir", desc: "Lambang ketahanan, perjalanan jauh, dan kemampuan bertahan dalam kondisi sulit." },
    { name: "Llama Andes", desc: "Melambangkan ketenangan, kekuatan, dan kehidupan di ketinggian." },
    { name: "Alpaca Berbulu", desc: "Simbol kehangatan, kenyamanan, dan kehidupan yang damai." },
    { name: "Zebra Loreng", desc: "Lambang keunikan, keseimbangan, dan kehidupan dalam komunitas." },
    { name: "Keledai Kerja", desc: "Mewakili ketekunan, kesabaran, dan kemampuan menanggung beban." },
    { name: "Walrus Gading", desc: "Simbol kekuatan, usia panjang, dan kehidupan di lingkungan ekstrem." },
    { name: "Anjing Laut", desc: "Lambang kelincahan, keceriaan, dan kemampuan beradaptasi di dua dunia." },
    { name: "Paus Pembunuh", desc: "Melambangkan kekuatan, kepemimpinan, dan kemampuan berburu yang efektif." },
    { name: "Lumba-lumba", desc: "Simbol kecerdasan, persahabatan, dan kebahagiaan." },
    { name: "Hiu Putih", desc: "Lambang kekuatan, ketegasan, dan kemampuan bertahan hidup." },
    { name: "Pari Manta", desc: "Mewakili keanggunan, kebebasan, dan kehidupan di lautan luas." },
    { name: "Gurita Raksasa", desc: "Simbol kecerdasan, kemampuan beradaptasi, dan kekuatan tersembunyi." },
    { name: "Cumi-cumi", desc: "Lambang misteri, perubahan warna, dan kemampuan menyamar." },
    { name: "Ubur-ubur", desc: "Melambangkan kelembutan, aliran kehidupan, dan ketenangan." },
    { name: "Bintang Laut", desc: "Simbol regenerasi, penyembuhan, dan kemampuan bangkit kembali." },
    { name: "Teripang Emas", desc: "Lambang kekayaan, kesehatan, dan nilai tersembunyi." },
    { name: "Kepiting Samurai", desc: "Mewakili perlindungan, kekuatan, dan kesiapan bertarung." },
    { name: "Lobster Merah", desc: "Simbol kekayaan, umur panjang, dan transformasi." },
    { name: "Udang Karang", desc: "Lambang ketekunan, kerja keras, dan kehidupan sederhana." },
    { name: "Ikan Koi", desc: "Melambangkan keberuntungan, ketekunan, dan kemampuan mengatasi rintangan." },
    { name: "Arwana Emas", desc: "Simbol kekayaan, prestise, dan keberuntungan finansial." },
    { name: "Ikan Mas Koki", desc: "Lambang kemakmuran, keindahan, dan kehidupan yang damai." },
    { name: "Ikan Cupang", desc: "Mewakili keberanian, semangat juang, dan keindahan yang mematikan." },
    { name: "Ikan Badut", desc: "Simbol persahabatan, perlindungan, dan kehidupan harmonis." },
    { name: "Ikan Layaran", desc: "Lambang kecepatan, kebebasan, dan petualangan di lautan." },
    { name: "Ikan Todak", desc: "Melambangkan ketajaman, kekuatan, dan kemampuan menyerang." },
    { name: "Ikan Terbang", desc: "Simbol kebebasan, kemampuan unik, dan melampaui batas." },
    { name: "Ikan Lele", desc: "Lambang ketahanan, kemampuan bertahan, dan kehidupan di dasar." },
    { name: "Ikan Gurame", desc: "Mewakili kemakmuran, ukuran besar, dan nilai ekonomis." },
    { name: "Ikan Nila", desc: "Simbol produktivitas, pertumbuhan cepat, dan ketahanan." },
    { name: "Ikan Bandeng", desc: "Lambang perjuangan, migrasi, dan kehidupan yang dinamis." },
    { name: "Ikan Salmon", desc: "Melambangkan perjuangan hidup, ketekunan, dan siklus kehidupan." },
    { name: "Ikan Tuna", desc: "Simbol kecepatan, kekuatan, dan nilai komersial." },
    { name: "Ikan Tongkol", desc: "Lambang pergerakan kelompok, kehidupan sosial, dan migrasi." },
    { name: "Ikan Tenggiri", desc: "Mewakili kecepatan, ketajaman, dan kemampuan berburu." },
    { name: "Ikan Kakap", desc: "Simbol kekuatan, ukuran besar, dan kehidupan di karang." },
    { name: "Ikan Kerapu", desc: "Lambang kesabaran, strategi berburu, dan kemampuan menyamar." },
    { name: "Ikan Baronang", desc: "Melambangkan kehidupan berkelompok, harmoni, dan pola makan vegetarian." },
    { name: "Ikan Bawal", desc: "Simbol kecepatan, bentuk unik, dan kemampuan berenang." },
    { name: "Ikan Belanak", desc: "Lambang adaptasi, kemampuan hidup di berbagai kondisi, dan ketahanan." },
    { name: "Ikan Gabus", desc: "Mewakili kekuatan, kemampuan bertahan hidup, dan nilai pengobatan." },
    { name: "Ikan Patin", desc: "Simbol kelembutan daging, nilai ekonomis, dan kehidupan di sungai." },
    { name: "Ikan Sarden", desc: "Lambang kehidupan berkelompok, migrasi besar, dan siklus hidup." },
    { name: "Ikan Makarel", desc: "Melambangkan kecepatan, kehidupan di laut lepas, dan nilai nutrisi." },
    { name: "Ikan Herring", desc: "Simbol kelimpahan, migrasi, dan dasar rantai makanan." },
    { name: "Ikan Kod", desc: "Lambang ketahanan, kehidupan di air dingin, dan nilai ekonomis." },
    { name: "Ikan Halibut", desc: "Mewakili kemampuan beradaptasi, bentuk unik, dan kehidupan di dasar." },
    { name: "Ikan Flounder", desc: "Simbol penyamaran, adaptasi, dan perubahan bentuk." },
    { name: "Ikan Sole", desc: "Lambang kelembutan, nilai kuliner, dan kehidupan dasar laut." },
    { name: "Ikan Plaice", desc: "Melambangkan pola unik, kehidupan di dasar, dan kemampuan beradaptasi." },
    { name: "Ikan Turbot", desc: "Simbol nilai tinggi, kelangkaan, dan kehidupan di perairan dalam." },
    { name: "Ikan John Dory", desc: "Lambang keunikan, nilai kuliner tinggi, dan penampilan mencolok." },
    { name: "Ikan Monkfish", desc: "Mewakili strategi berburu, penampilan unik, dan kehidupan di dasar." },
    { name: "Ikan Anglerfish", desc: "Simbol misteri, kehidupan di kedalaman, dan strategi bertahan hidup." },
    { name: "Ikan Dragonfish", desc: "Lambang kekuatan, kehidupan di kegelapan, dan kemampuan menghasilkan cahaya." },
    { name: "Ikan Viperfish", desc: "Melambangkan ketajaman, kemampuan berburu, dan kehidupan di kedalaman." },
    { name: "Ikan Gulper Eel", desc: "Simbol kemampuan menelan besar, adaptasi ekstrem, dan kehidupan laut dalam." },
    { name: "Ikan Oarfish", desc: "Lambang mitologi, penampakan langka, dan kehidupan misterius." },
    { name: "Ikan Sunfish", desc: "Mewakili keunikan bentuk, ukuran besar, dan kehidupan di permukaan." },
    { name: "Ikan Pufferfish", desc: "Simbol pertahanan diri, kemampuan mengembang, dan racun mematikan." },
    { name: "Ikan Blowfish", desc: "Lambang kemampuan bertahan, bentuk unik, dan adaptasi." },
    { name: "Ikan Porcupinefish", desc: "Melambangkan pertahanan ekstrem, duri tajam, dan kemampuan bertahan hidup." },
    { name: "Ikan Cowfish", desc: "Simbol keunikan, gerakan lambat, dan penampilan lucu." },
    { name: "Ikan Boxfish", desc: "Lambang struktur unik, gerakan khas, dan kemampuan bertahan." },
    { name: "Ikan Triggerfish", desc: "Mewakili ketegasan, kemampuan mengunci, dan kehidupan di terumbu karang." },
    { name: "Ikan Filefish", desc: "Simbol kemampuan menyamar, bentuk pipih, dan kehidupan dekat karang." },
    { name: "Ikan Surgeonfish", desc: "Lambang ketajaman, alat pertahanan, dan kehidupan berkelompok." },
    { name: "Ikan Tang", desc: "Melambangkan warna cerah, kehidupan aktif, dan peran dalam ekosistem karang." },
    { name: "Ikan Rabbitfish", desc: "Simbol kehati-hatian, kehidupan malam, dan pola makan herbivora." },
    { name: "Ikan Parrotfish", desc: "Lambang transformasi, peran dalam pembentukan pasir, dan warna cerah." },
    { name: "Ikan Wrasse", desc: "Mewakili keragaman, perubahan gender, dan kehidupan di karang." },
    { name: "Ikan Grouper", desc: "Simbol ukuran besar, umur panjang, dan kehidupan soliter." },
    { name: "Ikan Snapper", desc: "Lambang nilai ekonomis, kehidupan berkelompok, dan distribusi luas." },
    { name: "Ikan Emperor", desc: "Melambangkan kekuasaan, warna cerah, dan kehidupan di terumbu karang." },
    { name: "Ikan Sweetlips", desc: "Simbol gerakan lambat, penampilan unik, dan kehidupan malam." },
    { name: "Ikan Grunt", desc: "Lambang suara unik, kehidupan berkelompok, dan aktivitas malam." },
    { name: "Ikan Croaker", desc: "Mewakili kemampuan menghasilkan suara, kehidupan di dasar, dan nilai ekonomis." },
    { name: "Ikan Drum", desc: "Simbol suara drum, kehidupan di estuari, dan kemampuan beradaptasi." },
    { name: "Ikan Mullet", desc: "Lambang kemampuan melompat, kehidupan di permukaan, dan nilai ekonomis." },
    { name: "Ikan Barracuda", desc: "Melambangkan kecepatan, ketajaman gigi, dan kemampuan berburu." },
    { name: "Ikan Wahoo", desc: "Simbol kecepatan tinggi, nilai olahraga, dan kehidupan di laut terbuka." },
    { name: "Ikan Kingfish", desc: "Lambang kekuatan, nilai komersial, dan migrasi jarak jauh." },
    { name: "Ikan Amberjack", desc: "Mewakili kekuatan tarikan, nilai olahraga, dan kehidupan berkelompok." },
    { name: "Ikan Trevally", desc: "Simbol kecepatan, strategi berburu kelompok, dan kehidupan di perairan tropis." },
    { name: "Ikan Pompano", desc: "Lambang nilai kuliner tinggi, bentuk tubuh pipih, dan kehidupan di pantai." },
    { name: "Ikan Permit", desc: "Melambangkan tantangan, nilai olahraga tinggi, dan kehidupan di perairan dangkal." },
    { name: "Ikan Palometa", desc: "Simbol warna perak, gerakan cepat, dan kehidupan di perairan hangat." },
    { name: "Ikan Lookdown", desc: "Lambang penampilan unik, tubuh pipih vertikal, dan kehidupan di sekolah." },
    { name: "Ikan Moonfish", desc: "Mewakili bentuk bulat, warna perak, dan kehidupan di permukaan." },
    { name: "Ikan Opah", desc: "Simbol keunikan, darah hangat, dan kehidupan di laut dalam." },
    { name: "Ikan Louvar", desc: "Lambang kelangkaan, bentuk tubuh unik, dan kehidupan soliter." },
    { name: "Ikan Escolar", desc: "Melambangkan minyak alami, nilai kuliner, dan kehidupan di kedalaman." },
    { name: "Ikan Oilfish", desc: "Simbol kandungan minyak, efek pencernaan, dan kehidupan di laut dalam." },
    { name: "Ikan Snake Mackerel", desc: "Lambang bentuk seperti ular, kehidupan di laut terbuka, dan migrasi." },
    { name: "Ikan Lancetfish", desc: "Mewakili gigi tajam, bentuk tubuh memanjang, dan kehidupan di kedalaman." },
    { name: "Ikan Daggerfish", desc: "Simbol bentuk seperti belati, kehidupan di perairan dalam, dan migrasi vertikal." },
    { name: "Ikan Frostfish", desc: "Lambang toleransi dingin, kehidupan di perairan kutub, dan bentuk tubuh unik." },
    { name: "Ikan Scabbardfish", desc: "Melambangkan bentuk seperti pedang, kehidupan di laut dalam, dan migrasi." },
    { name: "Ikan Cutlassfish", desc: "Simbol bentuk seperti pedang, gigi tajam, dan kehidupan di perairan tropis." },
    { name: "Ikan Ribbonfish", desc: "Lambang bentuk pita, panjang ekstrem, dan kehidupan di laut dalam." },
    { name: "Ikan Hairtail", desc: "Mewakili bentuk seperti pita, warna perak, dan nilai ekonomis." },
    { name: "Ikan Saury", desc: "Simbol migrasi besar-besaran, nilai komersial, dan kehidupan di perairan dingin." },
    { name: "Ikan Needlefish", desc: "Lambang bentuk seperti jarum, kemampuan melompat, dan kehidupan di permukaan." },
    { name: "Ikan Halfbeak", desc: "Melambangkan rahang unik, kehidupan di permukaan, dan kemampuan melompat." },
    { name: "Ikan Flyingfish", desc: "Simbol kemampuan terbang, adaptasi unik, dan kehidupan di laut terbuka." },
    { name: "Ikan Garfish", desc: "Lambang bentuk memanjang, gigi tajam, dan kehidupan di perairan pantai." },
    { name: "Ikan Ballyhoo", desc: "Mewakili umpan alami, kehidupan di permukaan, dan nilai olahraga." },
    { name: "Ikan Houndfish", desc: "Simbol kecepatan, bentuk seperti tombak, dan kehidupan di perairan tropis." },
    { name: "Ikan Skipping", desc: "Lambang kemampuan melompat, kehidupan di permukaan, dan pola makan." },
    { name: "Ikan Bichir", desc: "Melambangkan bentuk purba, kemampuan bernapas udara, dan ketahanan." },
    { name: "Ikan Reedfish", desc: "Simbol bentuk seperti belut, kemampuan bernapas udara, dan kehidupan di rawa." },
    { name: "Ikan Sturgeon", desc: "Lambang umur panjang, nilai kaviar, dan kehidupan di sungai besar." },
    { name: "Ikan Paddlefish", desc: "Mewakili bentuk unik, moncong seperti dayung, dan kehidupan di sungai." },
    { name: "Ikan Bowfin", desc: "Simbol ketahanan, kemampuan bernapas udara, dan bentuk purba." },
    { name: "Ikan Garpike", desc: "Lambang bentuk seperti tombak, gigi tajam, dan kehidupan di air tawar." },
    { name: "Ikan Arowana", desc: "Melambangkan keberuntungan, nilai tinggi, dan kemampuan melompat." },
    { name: "Ikan Butterflyfish", desc: "Simbol keindahan, warna cerah, dan kehidupan di terumbu karang." },
    { name: "Ikan Angelfish", desc: "Lambang keanggunan, warna mencolok, dan kehidupan di karang." },
    { name: "Ikan Damselfish", desc: "Mewakili ukuran kecil, warna cerah, dan sifat teritorial." },
    { name: "Ikan Clownfish", desc: "Simbol simbiosis, warna cerah, dan ketahanan terhadap anemon." },
    { name: "Ikan Anemonefish", desc: "Lambang hubungan mutualisme, kehidupan dengan anemon, dan warna menarik." },
    { name: "Ikan Chromis", desc: "Melambangkan kehidupan berkelompok, warna biru-hijau, dan aktivitas di siang hari." },
    { name: "Ikan Demoiselle", desc: "Simbol ukuran kecil, warna cerah, dan kehidupan di karang." },
    { name: "Ikan Sergeant Major", desc: "Lambang garis-garis mencolok, kehidupan berkelompok, dan ketahanan." },
    { name: "Ikan Blue Devil", desc: "Mewakili warna biru cerah, sifat teritorial, dan kehidupan di karang." },
    { name: "Ikan Jewel Damsel", desc: "Simbol warna seperti permata, sifat agresif, dan kehidupan di terumbu." },
    { name: "Ikan Humbug", desc: "Lambang garis-garis hitam-putih, kehidupan berkelompok, dan aktivitas siang hari." },
    { name: "Ikan Talma", desc: "Melambangkan bentuk tubuh pipih, warna cerah, dan kehidupan di karang." },
    { name: "Ikan Sweeper", desc: "Simbol mata besar, aktivitas malam, dan kehidupan berkelompok." },
    { name: "Ikan Cardinalfish", desc: "Lambang mulut besar, sifat mengerami telur di mulut, dan kehidupan malam." },
    { name: "Ikan Bigeye", desc: "Mewakili mata besar, aktivitas malam, dan kehidupan di karang." },
    { name: "Ikan Glassfish", desc: "Simbol tubuh transparan, kehidupan berkelompok, dan adaptasi unik." },
    { name: "Ikan Fusilier", desc: "Lambang kehidupan berkelompok besar, warna biru cerah, dan aktivitas siang hari." },
    { name: "Ikan Goatfish", desc: "Melambangkan kumis sensorik, pencarian makanan di dasar, dan kehidupan berkelompok." },
    { name: "Ikan Emperor", desc: "Simbol ukuran besar, warna cerah, dan kehidupan di terumbu karang." },
    { name: "Ikan Sweetlips", desc: "Lambang gerakan lambat, penampilan unik, dan kehidupan malam." },
    { name: "Ikan Grunt", desc: "Mewakili suara unik, kehidupan berkelompok, dan aktivitas malam." },
    { name: "Ikan Croaker", desc: "Simbol kemampuan menghasilkan suara, kehidupan di dasar, dan nilai ekonomis." },
    { name: "Ikan Drum", desc: "Lambang suara drum, kehidupan di estuari, dan kemampuan beradaptasi." },
    { name: "Ikan Mullet", desc: "Melambangkan kemampuan melompat, kehidupan di permukaan, dan nilai ekonomis." },
    { name: "Ikan Barracuda", desc: "Simbol kecepatan, ketajaman gigi, dan kemampuan berburu." },
    { name: "Ikan Wahoo", desc: "Lambang kecepatan tinggi, nilai olahraga, dan kehidupan di laut terbuka." },
    { name: "Ikan Kingfish", desc: "Mewakili kekuatan, nilai komersial, dan migrasi jarak jauh." },
    { name: "Ikan Amberjack", desc: "Simbol kekuatan tarikan, nilai olahraga, dan kehidupan berkelompok." },
    { name: "Ikan Trevally", desc: "Lambang kecepatan, strategi berburu kelompok, dan kehidupan di perairan tropis." },
    { name: "Ikan Pompano", desc: "Melambangkan nilai kuliner tinggi, bentuk tubuh pipih, dan kehidupan di pantai." },
    { name: "Ikan Permit", desc: "Simbol tantangan, nilai olahraga tinggi, dan kehidupan di perairan dangkal." },
    { name: "Ikan Palometa", desc: "Lambang warna perak, gerakan cepat, dan kehidupan di perairan hangat." },
    { name: "Ikan Lookdown", desc: "Mewakili penampilan unik, tubuh pipih vertikal, dan kehidupan di sekolah." },
    { name: "Ikan Moonfish", desc: "Simbol bentuk bulat, warna perak, dan kehidupan di permukaan." },
    { name: "Ikan Opah", desc: "Lambang keunikan, darah hangat, dan kehidupan di laut dalam." },
    { name: "Ikan Louvar", desc: "Melambangkan kelangkaan, bentuk tubuh unik, dan kehidupan soliter." },
    { name: "Ikan Escolar", desc: "Simbol minyak alami, nilai kuliner, dan kehidupan di kedalaman." },
    { name: "Ikan Oilfish", desc: "Lambang kandungan minyak, efek pencernaan, dan kehidupan di laut dalam." },
    { name: "Ikan Snake Mackerel", desc: "Mewakili bentuk seperti ular, kehidupan di laut terbuka, dan migrasi." },
    { name: "Ikan Lancetfish", desc: "Simbol gigi tajam, bentuk tubuh memanjang, dan kehidupan di kedalaman." },
    { name: "Ikan Daggerfish", desc: "Lambang bentuk seperti belati, kehidupan di perairan dalam, dan migrasi vertikal." },
    { name: "Ikan Frostfish", desc: "Melambangkan toleransi dingin, kehidupan di perairan kutub, dan bentuk tubuh unik." },
    { name: "Ikan Scabbardfish", desc: "Simbol bentuk seperti pedang, kehidupan di laut dalam, dan migrasi." },
    { name: "Ikan Cutlassfish", desc: "Lambang bentuk seperti pedang, gigi tajam, dan kehidupan di perairan tropis." },
    { name: "Ikan Ribbonfish", desc: "Mewakili bentuk pita, panjang ekstrem, dan kehidupan di laut dalam." },
    { name: "Ikan Hairtail", desc: "Simbol bentuk seperti pita, warna perak, dan nilai ekonomis." },
    { name: "Ikan Saury", desc: "Lambang migrasi besar-besaran, nilai komersial, dan kehidupan di perairan dingin." },
    { name: "Ikan Needlefish", desc: "Melambangkan bentuk seperti jarum, kemampuan melompat, dan kehidupan di permukaan." },
    { name: "Ikan Halfbeak", desc: "Simbol rahang unik, kehidupan di permukaan, dan kemampuan melompat." },
    { name: "Ikan Flyingfish", desc: "Lambang kemampuan terbang, adaptasi unik, dan kehidupan di laut terbuka." },
    { name: "Ikan Garfish", desc: "Mewakili bentuk memanjang, gigi tajam, dan kehidupan di perairan pantai." },
    { name: "Ikan Ballyhoo", desc: "Simbol umpan alami, kehidupan di permukaan, dan nilai olahraga." },
    { name: "Ikan Houndfish", desc: "Lambang kecepatan, bentuk seperti tombak, dan kehidupan di perairan tropis." },
    { name: "Ikan Skipping", desc: "Melambangkan kemampuan melompat, kehidupan di permukaan, dan pola makan." },
    { name: "Ikan Bichir", desc: "Simbol bentuk purba, kemampuan bernapas udara, dan ketahanan." },
    { name: "Ikan Reedfish", desc: "Lambang bentuk seperti belut, kemampuan bernapas udara, dan kehidupan di rawa." },
    { name: "Ikan Sturgeon", desc: "Mewakili umur panjang, nilai kaviar, dan kehidupan di sungai besar." },
    { name: "Ikan Paddlefish", desc: "Simbol bentuk unik, moncong seperti dayung, dan kehidupan di sungai." },
    { name: "Ikan Bowfin", desc: "Lambang ketahanan, kemampuan bernapas udara, dan bentuk purba." },
    { name: "Ikan Garpike", desc: "Melambangkan bentuk seperti tombak, gigi tajam, dan kehidupan di air tawar." },
    { name: "Ikan Arowana", desc: "Simbol keberuntungan, nilai tinggi, dan kemampuan melompat." },
    { name: "Ikan Butterflyfish", desc: "Lambang keindahan, warna cerah, dan kehidupan di terumbu karang." },
    { name: "Ikan Angelfish", desc: "Mewakili keanggunan, warna mencolok, dan kehidupan di karang." },
    { name: "Ikan Damselfish", desc: "Simbol ukuran kecil, warna cerah, dan sifat teritorial." },
    { name: "Ikan Clownfish", desc: "Lambang simbiosis, warna cerah, dan ketahanan terhadap anemon." },
    { name: "Ikan Anemonefish", desc: "Melambangkan hubungan mutualisme, kehidupan dengan anemon, dan warna menarik." },
    { name: "Ikan Chromis", desc: "Simbol kehidupan berkelompok, warna biru-hijau, dan aktivitas di siang hari." },
    { name: "Ikan Demoiselle", desc: "Lambang ukuran kecil, warna cerah, dan kehidupan di karang." },
    { name: "Ikan Sergeant Major", desc: "Mewakili garis-garis mencolok, kehidupan berkelompok, dan ketahanan." },
    { name: "Ikan Blue Devil", desc: "Simbol warna biru cerah, sifat teritorial, dan kehidupan di karang." },
    { name: "Ikan Jewel Damsel", desc: "Lambang warna seperti permata, sifat agresif, dan kehidupan di terumbu." },
    { name: "Ikan Humbug", desc: "Melambangkan garis-garis hitam-putih, kehidupan berkelompok, dan aktivitas siang hari." },
    { name: "Ikan Talma", desc: "Simbol bentuk tubuh pipih, warna cerah, dan kehidupan di karang." },
    { name: "Ikan Sweeper", desc: "Lambang mata besar, aktivitas malam, dan kehidupan berkelompok." },
    { name: "Ikan Cardinalfish", desc: "Mewakili mulut besar, sifat mengerami telur di mulut, dan kehidupan malam." },
    { name: "Ikan Bigeye", desc: "Simbol mata besar, aktivitas malam, dan kehidupan di karang." },
    { name: "Ikan Glassfish", desc: "Lambang tubuh transparan, kehidupan berkelompok, dan adaptasi unik." },
    { name: "Ikan Fusilier", desc: "Melambangkan kehidupan berkelompok besar, warna biru cerah, dan aktivitas siang hari." },
    { name: "Ikan Goatfish", desc: "Simbol kumis sensorik, pencarian makanan di dasar, dan kehidupan berkelompok." },
    { name: "Ikan Emperor", desc: "Lambang ukuran besar, warna cerah, dan kehidupan di terumbu karang." },
    { name: "Ikan Sweetlips", desc: "Mewakili gerakan lambat, penampilan unik, dan kehidupan malam." },
    { name: "Ikan Grunt", desc: "Simbol suara unik, kehidupan berkelompok, dan aktivitas malam." },
    { name: "Ikan Croaker", desc: "Lambang kemampuan menghasilkan suara, kehidupan di dasar, dan nilai ekonomis." },
    { name: "Ikan Drum", desc: "Melambangkan suara drum, kehidupan di estuari, dan kemampuan beradaptasi." },
    { name: "Ikan Mullet", desc: "Simbol kemampuan melompat, kehidupan di permukaan, dan nilai ekonomis." },
    { name: "Ikan Barracuda", desc: "Lambang kecepatan, ketajaman gigi, dan kemampuan berburu." },
    { name: "Ikan Wahoo", desc: "Mewakili kecepatan tinggi, nilai olahraga, dan kehidupan di laut terbuka." },
    { name: "Ikan Kingfish", desc: "Simbol kekuatan, nilai komersial, dan migrasi jarak jauh." },
    { name: "Ikan Amberjack", desc: "Lambang kekuatan tarikan, nilai olahraga, dan kehidupan berkelompok." },
    { name: "Ikan Trevally", desc: "Melambangkan kecepatan, strategi berburu kelompok, dan kehidupan di perairan tropis." },
    { name: "Ikan Pompano", desc: "Simbol nilai kuliner tinggi, bentuk tubuh pipih, dan kehidupan di pantai." },
    { name: "Ikan Permit", desc: "Lambang tantangan, nilai olahraga tinggi, dan kehidupan di perairan dangkal." },
    { name: "Ikan Palometa", desc: "Mewakili warna perak, gerakan cepat, dan kehidupan di perairan hangat." },
    { name: "Ikan Lookdown", desc: "Simbol penampilan unik, tubuh pipih vertikal, dan kehidupan di sekolah." },
    { name: "Ikan Moonfish", desc: "Lambang bentuk bulat, warna perak, dan kehidupan di permukaan." },
    { name: "Ikan Opah", desc: "Melambangkan keunikan, darah hangat, dan kehidupan di laut dalam." },
    { name: "Ikan Louvar", desc: "Simbol kelangkaan, bentuk tubuh unik, dan kehidupan soliter." },
    { name: "Ikan Escolar", desc: "Lambang minyak alami, nilai kuliner, dan kehidupan di kedalaman." },
    { name: "Ikan Oilfish", desc: "Mewakili kandungan minyak, efek pencernaan, dan kehidupan di laut dalam." },
    { name: "Ikan Snake Mackerel", desc: "Simbol bentuk seperti ular, kehidupan di laut terbuka, dan migrasi." },
    { name: "Ikan Lancetfish", desc: "Lambang gigi tajam, bentuk tubuh memanjang, dan kehidupan di kedalaman." },
    { name: "Ikan Daggerfish", desc: "Melambangkan bentuk seperti belati, kehidupan di perairan dalam, dan migrasi vertikal." },
    { name: "Ikan Frostfish", desc: "Simbol toleransi dingin, kehidupan di perairan kutub, dan bentuk tubuh unik." },
    { name: "Ikan Scabbardfish", desc: "Lambang bentuk seperti pedang, kehidupan di laut dalam, dan migrasi." },
    { name: "Ikan Cutlassfish", desc: "Mewakili bentuk seperti pedang, gigi tajam, dan kehidupan di perairan tropis." },
    { name: "Ikan Ribbonfish", desc: "Simbol bentuk pita, panjang ekstrem, dan kehidupan di laut dalam." },
    { name: "Ikan Hairtail", desc: "Lambang bentuk seperti pita, warna perak, dan nilai ekonomis." },
    { name: "Ikan Saury", desc: "Melambangkan migrasi besar-besaran, nilai komersial, dan kehidupan di perairan dingin." },
    { name: "Ikan Needlefish", desc: "Simbol bentuk seperti jarum, kemampuan melompat, dan kehidupan di permukaan." },
    { name: "Ikan Halfbeak", desc: "Lambang rahang unik, kehidupan di permukaan, dan kemampuan melompat." },
    { name: "Ikan Flyingfish", desc: "Mewakili kemampuan terbang, adaptasi unik, dan kehidupan di laut terbuka." },
    { name: "Ikan Garfish", desc: "Simbol bentuk memanjang, gigi tajam, dan kehidupan di perairan pantai." },
    { name: "Ikan Ballyhoo", desc: "Lambang umpan alami, kehidupan di permukaan, dan nilai olahraga." },
    { name: "Ikan Houndfish", desc: "Melambangkan kecepatan, bentuk seperti tombak, dan kehidupan di perairan tropis." },
    { name: "Ikan Skipping", desc: "Simbol kemampuan melompat, kehidupan di permukaan, dan pola makan." },
    { name: "Ikan Bichir", desc: "Lambang bentuk purba, kemampuan bernapas udara, dan ketahanan." },
    { name: "Ikan Reedfish", desc: "Mewakili bentuk seperti belut, kemampuan bernapas udara, dan kehidupan di rawa." },
    { name: "Ikan Sturgeon", desc: "Simbol umur panjang, nilai kaviar, dan kehidupan di sungai besar." },
    { name: "Ikan Paddlefish", desc: "Lambang bentuk unik, moncong seperti dayung, dan kehidupan di sungai." },
    { name: "Ikan Bowfin", desc: "Melambangkan ketahanan, kemampuan bernapas udara, dan bentuk purba." },
    { name: "Ikan Garpike", desc: "Simbol bentuk seperti tombak, gigi tajam, dan kehidupan di air tawar." },
    { name: "Ikan Arowana", desc: "Lambang keberuntungan, nilai tinggi, dan kemampuan melompat." },
    { name: "Ikan Butterflyfish", desc: "Mewakili keindahan, warna cerah, dan kehidupan di terumbu karang." },
    { name: "Ikan Angelfish", desc: "Simbol keanggunan, warna mencolok, dan kehidupan di karang." },
    { name: "Ikan Damselfish", desc: "Lambang ukuran kecil, warna cerah, dan sifat teritorial." },
    { name: "Ikan Clownfish", desc: "Melambangkan simbiosis, warna cerah, dan ketahanan terhadap anemon." },
    { name: "Ikan Anemonefish", desc: "Simbol hubungan mutualisme, kehidupan dengan anemon, dan warna menarik." },
    { name: "Ikan Chromis", desc: "Lambang kehidupan berkelompok, warna biru-hijau, dan aktivitas di siang hari." },
    { name: "Ikan Demoiselle", desc: "Mewakili ukuran kecil, warna cerah, dan kehidupan di karang." },
    { name: "Ikan Sergeant Major", desc: "Simbol garis-garis mencolok, kehidupan berkelompok, dan ketahanan." },
    { name: "Ikan Blue Devil", desc: "Lambang warna biru cerah, sifat teritorial, dan kehidupan di karang." },
    { name: "Ikan Jewel Damsel", desc: "Melambangkan warna seperti permata, sifat agresif, dan kehidupan di terumbu." },
    { name: "Ikan Humbug", desc: "Simbol garis-garis hitam-putih, kehidupan berkelompok, dan aktivitas siang hari." },
    { name: "Ikan Talma", desc: "Lambang bentuk tubuh pipih, warna cerah, dan kehidupan di karang." },
    { name: "Ikan Sweeper", desc: "Mewakili mata besar, aktivitas malam, dan kehidupan berkelompok." },
    { name: "Ikan Cardinalfish", desc: "Simbol mulut besar, sifat mengerami telur di mulut, dan kehidupan malam." },
    { name: "Ikan Bigeye", desc: "Lambang mata besar, aktivitas malam, dan kehidupan di karang." },
    { name: "Ikan Glassfish", desc: "Melambangkan tubuh transparan, kehidupan berkelompok, dan adaptasi unik." },
];

async function cekKhodam(nama) {
    // Jika Anda ingin menghubungkan ke API asli di https://cek-kodam-bay.vercel.app/
    // Gantilah kode di bawah ini dengan panggilan axios.get atau axios.post
    // Contoh: const response = await axios.get(`https://cek-kodam-bay.vercel.app/api?nama=${encodeURIComponent(nama)}`);
    // return response.data;

    // Kode berikut adalah SIMULASI lokal karena API target tidak dapat diakses
    if (!nama || nama.trim().length === 0) {
        throw new Error('Nama wajib diisi.');
    }

    // Generate khodam deterministik namun acak berdasarkan nama input
    const seed = nama.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
    const selectedIndex = seed % khodamList.length;
    const selectedKhodam = khodamList[selectedIndex];

    // Simulasi delay jaringan
    await new Promise(resolve => setTimeout(resolve, 300));

    return {
        nama: nama.trim(),
        khodam: selectedKhodam.name,
        deskripsi: selectedKhodam.desc,
        catatan: "Hasil ini adalah simulasi. Untuk hasil dari sumber eksternal, gunakan API asli di https://cek-kodam-bay.vercel.app/",
        timestamp: new Date().toISOString()
    };
}

module.exports = function(app) {
    app.get("/random/cekkhodam", async (req, res) => {
        const { nama } = req.query;
        
        if (!nama) {
            return res.status(400).json({
                status: false,
                creator: "aerixxx",
                message: "Parameter 'nama' wajib diisi."
            });
        }

        try {
            const result = await cekKhodam(nama);
            
            return res.json({
                status: true,
                creator: "aerixxx",
                result: result
            });
            
        } catch (error) {
            return res.status(500).json({
                status: false,
                creator: "aerixxx",
                message: error.message || "Gagal melakukan pengecekan khodam"
            });
        }
    });
};